# Generated by Django 4.1 on 2024-04-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_article_posted_article_slug_article_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="subtitle",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="thumb",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="posted",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.category",
            ),
        ),
    ]
