# Generated by Django 4.1 on 2024-04-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_category_article_subtitle_article_thumb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="shouldBeDisplayed",
            field=models.BooleanField(default=False),
        ),
    ]
