# Generated by Django 4.1 on 2024-04-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_category_shouldbedisplayed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumb",
            field=models.ImageField(null=True, upload_to="img"),
        ),
    ]
