# Generated by Django 4.1 on 2024-04-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_article_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
