# Generated by Django 4.1 on 2024-05-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_article_highlight_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="viewCount",
            field=models.IntegerField(default=0),
        ),
    ]
