# Generated by Django 4.1 on 2024-05-10 00:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_article_viewcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
